USE milicic;

INSERT INTO einstellung(firmenname, beschreibung, impressum, hinweise) values("Company", "beschreibung", "impressum", "Sämtliche Inhalte sowie die Struktur der Website sind urheberrechtlich geschützt.Die Verwendung von Texten und Bildmaterial (auch auszugsweise) zu privaten und/oder kommerziellen Zwecken bedarf der vorherigen ausdrücklichen schriftlichen Zustimmung.");
INSERT INTO design(headerfarbe, footerfarbe, akzentfarbe, slider1, slider2, slider3) values("#009688", "#e91e63", "#f44336", "assets/img/slider/default.png", "assets/img/slider/default.png", "assets/img/slider/default.png");


INSERT INTO farbe(name, hexcode) values("red lighten-5", "#ffebee");
INSERT INTO farbe(name, hexcode) values("red lighten-4", "#ffcdd2");
INSERT INTO farbe(name, hexcode) values("red lighten-3", "#ef9a9a");
INSERT INTO farbe(name, hexcode) values("red lighten-2", "#e57373");
INSERT INTO farbe(name, hexcode) values("red lighten-1", "#ef5350");
INSERT INTO farbe(name, hexcode) values("red", "#f44336");
INSERT INTO farbe(name, hexcode) values("red darken-1", "#e53935");
INSERT INTO farbe(name, hexcode) values("red darken-2", "#d32f2f");
INSERT INTO farbe(name, hexcode) values("red darken-3", "#c62828");
INSERT INTO farbe(name, hexcode) values("red darken-4", "#b71c1c");
INSERT INTO farbe(name, hexcode) values("red accent-1", "#ff8a80");
INSERT INTO farbe(name, hexcode) values("red accent-2", "#ff5252");
INSERT INTO farbe(name, hexcode) values("red accent-3", "#ff1744");
INSERT INTO farbe(name, hexcode) values("red accent-4", "#d50000");
INSERT INTO farbe(name, hexcode) values("pink lighten-5", "#fce4ec");
INSERT INTO farbe(name, hexcode) values("pink lighten-4", "#f8bbd0");
INSERT INTO farbe(name, hexcode) values("pink lighten-3", "#f48fb1");
INSERT INTO farbe(name, hexcode) values("pink lighten-2", "#f06292");
INSERT INTO farbe(name, hexcode) values("pink lighten-1", "#ec407a");
INSERT INTO farbe(name, hexcode) values("pink", "#e91e63");
INSERT INTO farbe(name, hexcode) values("pink darken-1", "#d81b60");
INSERT INTO farbe(name, hexcode) values("pink darken-2", "#c2185b");
INSERT INTO farbe(name, hexcode) values("pink darken-3", "#ad1457");
INSERT INTO farbe(name, hexcode) values("pink darken-4", "#880e4f");
INSERT INTO farbe(name, hexcode) values("pink accent-1", "#ff80ab");
INSERT INTO farbe(name, hexcode) values("pink accent-2", "#ff4081");
INSERT INTO farbe(name, hexcode) values("pink accent-3", "#f50057");
INSERT INTO farbe(name, hexcode) values("pink accent-4", "#c51162");
INSERT INTO farbe(name, hexcode) values("purple lighten-5", "#f3e5f5");
INSERT INTO farbe(name, hexcode) values("purple lighten-4", "#e1bee7");
INSERT INTO farbe(name, hexcode) values("purple lighten-3", "#ce93d8");
INSERT INTO farbe(name, hexcode) values("purple lighten-2", "#ba68c8");
INSERT INTO farbe(name, hexcode) values("purple lighten-1", "#ab47bc");
INSERT INTO farbe(name, hexcode) values("purple", "#9c27b0");
INSERT INTO farbe(name, hexcode) values("purple darken-1", "#8e24aa");
INSERT INTO farbe(name, hexcode) values("purple darken-2", "#7b1fa2");
INSERT INTO farbe(name, hexcode) values("purple darken-3", "#6a1b9a");
INSERT INTO farbe(name, hexcode) values("purple darken-4", "#4a148c");
INSERT INTO farbe(name, hexcode) values("purple accent-1", "#ea80fc");
INSERT INTO farbe(name, hexcode) values("purple accent-2", "#e040fb");
INSERT INTO farbe(name, hexcode) values("purple accent-3", "#d500f9");
INSERT INTO farbe(name, hexcode) values("purple accent-4", "#aa00ff");
INSERT INTO farbe(name, hexcode) values("deep-purple lighten-5", "#ede7f6");
INSERT INTO farbe(name, hexcode) values("deep-purple lighten-4", "#d1c4e9");
INSERT INTO farbe(name, hexcode) values("deep-purple lighten-3", "#b39ddb");
INSERT INTO farbe(name, hexcode) values("deep-purple lighten-2", "#9575cd");
INSERT INTO farbe(name, hexcode) values("deep-purple lighten-1", "#7e57c2");
INSERT INTO farbe(name, hexcode) values("deep-purple", "#673ab7");
INSERT INTO farbe(name, hexcode) values("deep-purple darken-1", "#5e35b1");
INSERT INTO farbe(name, hexcode) values("deep-purple darken-2", "#512da8");
INSERT INTO farbe(name, hexcode) values("deep-purple darken-3", "#4527a0");
INSERT INTO farbe(name, hexcode) values("deep-purple darken-4", "#311b92");
INSERT INTO farbe(name, hexcode) values("deep-purple accent-1", "#b388ff");
INSERT INTO farbe(name, hexcode) values("deep-purple accent-2", "#7c4dff");
INSERT INTO farbe(name, hexcode) values("deep-purple accent-3", "#651fff");
INSERT INTO farbe(name, hexcode) values("deep-purple accent-4", "#6200ea");
INSERT INTO farbe(name, hexcode) values("indigo lighten-5", "#e8eaf6");
INSERT INTO farbe(name, hexcode) values("indigo lighten-4", "#c5cae9");
INSERT INTO farbe(name, hexcode) values("indigo lighten-3", "#9fa8da");
INSERT INTO farbe(name, hexcode) values("indigo lighten-2", "#7986cb");
INSERT INTO farbe(name, hexcode) values("indigo lighten-1", "#5c6bc0");
INSERT INTO farbe(name, hexcode) values("indigo", "#3f51b5");
INSERT INTO farbe(name, hexcode) values("indigo darken-1", "#3949ab");
INSERT INTO farbe(name, hexcode) values("indigo darken-2", "#303f9f");
INSERT INTO farbe(name, hexcode) values("indigo darken-3", "#283593");
INSERT INTO farbe(name, hexcode) values("indigo darken-4", "#1a237e");
INSERT INTO farbe(name, hexcode) values("indigo accent-1", "#8c9eff");
INSERT INTO farbe(name, hexcode) values("indigo accent-2", "#536dfe");
INSERT INTO farbe(name, hexcode) values("indigo accent-3", "#3d5afe");
INSERT INTO farbe(name, hexcode) values("indigo accent-4", "#304ffe");
INSERT INTO farbe(name, hexcode) values("blue lighten-5", "#e3f2fd");
INSERT INTO farbe(name, hexcode) values("blue lighten-4", "#bbdefb");
INSERT INTO farbe(name, hexcode) values("blue lighten-3", "#90caf9");
INSERT INTO farbe(name, hexcode) values("blue lighten-2", "#64b5f6");
INSERT INTO farbe(name, hexcode) values("blue lighten-1", "#42a5f5");
INSERT INTO farbe(name, hexcode) values("blue", "#2196f3");
INSERT INTO farbe(name, hexcode) values("blue darken-1", "#1e88e5");
INSERT INTO farbe(name, hexcode) values("blue darken-2", "#1976d2");
INSERT INTO farbe(name, hexcode) values("blue darken-3", "#1565c0");
INSERT INTO farbe(name, hexcode) values("blue darken-4", "#0d47a1");
INSERT INTO farbe(name, hexcode) values("blue accent-1", "#82b1ff");
INSERT INTO farbe(name, hexcode) values("blue accent-2", "#448aff");
INSERT INTO farbe(name, hexcode) values("blue accent-3", "#2979ff");
INSERT INTO farbe(name, hexcode) values("blue accent-4", "#2962ff");
INSERT INTO farbe(name, hexcode) values("light-blue lighten-5", "#e1f5fe");
INSERT INTO farbe(name, hexcode) values("light-blue lighten-4", "#b3e5fc");
INSERT INTO farbe(name, hexcode) values("light-blue lighten-3", "#81d4fa");
INSERT INTO farbe(name, hexcode) values("light-blue lighten-2", "#4fc3f7");
INSERT INTO farbe(name, hexcode) values("light-blue lighten-1", "#29b6f6");
INSERT INTO farbe(name, hexcode) values("light-blue", "#03a9f4");
INSERT INTO farbe(name, hexcode) values("light-blue darken-1", "#039be5");
INSERT INTO farbe(name, hexcode) values("light-blue darken-2", "#0288d1");
INSERT INTO farbe(name, hexcode) values("light-blue darken-3", "#0277bd");
INSERT INTO farbe(name, hexcode) values("light-blue darken-4", "#01579b");
INSERT INTO farbe(name, hexcode) values("light-blue accent-1", "#80d8ff");
INSERT INTO farbe(name, hexcode) values("light-blue accent-2", "#40c4ff");
INSERT INTO farbe(name, hexcode) values("light-blue accent-3", "#00b0ff");
INSERT INTO farbe(name, hexcode) values("light-blue accent-4", "#0091ea");
INSERT INTO farbe(name, hexcode) values("cyan lighten-5", "#e0f7fa");
INSERT INTO farbe(name, hexcode) values("cyan lighten-4", "#b2ebf2");
INSERT INTO farbe(name, hexcode) values("cyan lighten-3", "#80deea");
INSERT INTO farbe(name, hexcode) values("cyan lighten-2", "#4dd0e1");
INSERT INTO farbe(name, hexcode) values("cyan lighten-1", "#26c6da");
INSERT INTO farbe(name, hexcode) values("cyan", "#00bcd4");
INSERT INTO farbe(name, hexcode) values("cyan darken-1", "#00acc1");
INSERT INTO farbe(name, hexcode) values("cyan darken-2", "#0097a7");
INSERT INTO farbe(name, hexcode) values("cyan darken-3", "#00838f");
INSERT INTO farbe(name, hexcode) values("cyan darken-4", "#006064");
INSERT INTO farbe(name, hexcode) values("cyan accent-1", "#84ffff");
INSERT INTO farbe(name, hexcode) values("cyan accent-2", "#18ffff");
INSERT INTO farbe(name, hexcode) values("cyan accent-3", "#00e5ff");
INSERT INTO farbe(name, hexcode) values("cyan accent-4", "#00b8d4");
INSERT INTO farbe(name, hexcode) values("teal lighten-5", "#e0f2f1");
INSERT INTO farbe(name, hexcode) values("teal lighten-4", "#b2dfdb");
INSERT INTO farbe(name, hexcode) values("teal lighten-3", "#80cbc4");
INSERT INTO farbe(name, hexcode) values("teal lighten-2", "#4db6ac");
INSERT INTO farbe(name, hexcode) values("teal lighten-1", "#26a69a");
INSERT INTO farbe(name, hexcode) values("teal", "#009688");
INSERT INTO farbe(name, hexcode) values("teal darken-1", "#00897b");
INSERT INTO farbe(name, hexcode) values("teal darken-2", "#00796b");
INSERT INTO farbe(name, hexcode) values("teal darken-3", "#00695c");
INSERT INTO farbe(name, hexcode) values("teal darken-4", "#004d40");
INSERT INTO farbe(name, hexcode) values("teal accent-1", "#a7ffeb");
INSERT INTO farbe(name, hexcode) values("teal accent-2", "#64ffda");
INSERT INTO farbe(name, hexcode) values("teal accent-3", "#1de9b6");
INSERT INTO farbe(name, hexcode) values("teal accent-4", "#00bfa5");
INSERT INTO farbe(name, hexcode) values("green lighten-5", "#e8f5e9");
INSERT INTO farbe(name, hexcode) values("green lighten-4", "#c8e6c9");
INSERT INTO farbe(name, hexcode) values("green lighten-3", "#a5d6a7");
INSERT INTO farbe(name, hexcode) values("green lighten-2", "#81c784");
INSERT INTO farbe(name, hexcode) values("green lighten-1", "#66bb6a");
INSERT INTO farbe(name, hexcode) values("green", "#4caf50");
INSERT INTO farbe(name, hexcode) values("green darken-1", "#43a047");
INSERT INTO farbe(name, hexcode) values("green darken-2", "#388e3c");
INSERT INTO farbe(name, hexcode) values("green darken-3", "#2e7d32");
INSERT INTO farbe(name, hexcode) values("green darken-4", "#1b5e20");
INSERT INTO farbe(name, hexcode) values("green accent-1", "#b9f6ca");
INSERT INTO farbe(name, hexcode) values("green accent-2", "#69f0ae");
INSERT INTO farbe(name, hexcode) values("green accent-3", "#00e676");
INSERT INTO farbe(name, hexcode) values("green accent-4", "#00c853");
INSERT INTO farbe(name, hexcode) values("light-green lighten-5", "#f1f8e9");
INSERT INTO farbe(name, hexcode) values("light-green lighten-4", "#dcedc8");
INSERT INTO farbe(name, hexcode) values("light-green lighten-3", "#c5e1a5");
INSERT INTO farbe(name, hexcode) values("light-green lighten-2", "#aed581");
INSERT INTO farbe(name, hexcode) values("light-green lighten-1", "#9ccc65");
INSERT INTO farbe(name, hexcode) values("light-green", "#8bc34a");
INSERT INTO farbe(name, hexcode) values("light-green darken-1", "#7cb342");
INSERT INTO farbe(name, hexcode) values("light-green darken-2", "#689f38");
INSERT INTO farbe(name, hexcode) values("light-green darken-3", "#558b2f");
INSERT INTO farbe(name, hexcode) values("light-green darken-4", "#33691e");
INSERT INTO farbe(name, hexcode) values("light-green accent-1", "#ccff90");
INSERT INTO farbe(name, hexcode) values("light-green accent-2", "#b2ff59");
INSERT INTO farbe(name, hexcode) values("light-green accent-3", "#76ff03");
INSERT INTO farbe(name, hexcode) values("light-green accent-4", "#64dd17");
INSERT INTO farbe(name, hexcode) values("lime lighten-5", "#f9fbe7");
INSERT INTO farbe(name, hexcode) values("lime lighten-4", "#f0f4c3");
INSERT INTO farbe(name, hexcode) values("lime lighten-3", "#e6ee9c");
INSERT INTO farbe(name, hexcode) values("lime lighten-2", "#dce775");
INSERT INTO farbe(name, hexcode) values("lime lighten-1", "#d4e157");
INSERT INTO farbe(name, hexcode) values("lime", "#cddc39");
INSERT INTO farbe(name, hexcode) values("lime darken-1", "#c0ca33");
INSERT INTO farbe(name, hexcode) values("lime darken-2", "#afb42b");
INSERT INTO farbe(name, hexcode) values("lime darken-3", "#9e9d24");
INSERT INTO farbe(name, hexcode) values("lime darken-4", "#827717");
INSERT INTO farbe(name, hexcode) values("lime accent-1", "#f4ff81");
INSERT INTO farbe(name, hexcode) values("lime accent-2", "#eeff41");
INSERT INTO farbe(name, hexcode) values("lime accent-3", "#c6ff00");
INSERT INTO farbe(name, hexcode) values("lime accent-4", "#aeea00");
INSERT INTO farbe(name, hexcode) values("yellow lighten-5", "#fffde7");
INSERT INTO farbe(name, hexcode) values("yellow lighten-4", "#fff9c4");
INSERT INTO farbe(name, hexcode) values("yellow lighten-3", "#fff59d");
INSERT INTO farbe(name, hexcode) values("yellow lighten-2", "#fff176");
INSERT INTO farbe(name, hexcode) values("yellow lighten-1", "#ffee58");
INSERT INTO farbe(name, hexcode) values("yellow", "#ffeb3b");
INSERT INTO farbe(name, hexcode) values("yellow darken-1", "#fdd835");
INSERT INTO farbe(name, hexcode) values("yellow darken-2", "#fbc02d");
INSERT INTO farbe(name, hexcode) values("yellow darken-3", "#f9a825");
INSERT INTO farbe(name, hexcode) values("yellow darken-4", "#f57f17");
INSERT INTO farbe(name, hexcode) values("yellow accent-1", "#ffff8d");
INSERT INTO farbe(name, hexcode) values("yellow accent-2", "#ffff00");
INSERT INTO farbe(name, hexcode) values("yellow accent-3", "#ffea00");
INSERT INTO farbe(name, hexcode) values("yellow accent-4", "#ffd600");
INSERT INTO farbe(name, hexcode) values("amber lighten-5", "#fff8e1");
INSERT INTO farbe(name, hexcode) values("amber lighten-4", "#ffecb3");
INSERT INTO farbe(name, hexcode) values("amber lighten-3", "#ffe082");
INSERT INTO farbe(name, hexcode) values("amber lighten-2", "#ffd54f");
INSERT INTO farbe(name, hexcode) values("amber lighten-1", "#ffca28");
INSERT INTO farbe(name, hexcode) values("amber", "#ffc107");
INSERT INTO farbe(name, hexcode) values("amber darken-1", "#ffb300");
INSERT INTO farbe(name, hexcode) values("amber darken-2", "#ffa000");
INSERT INTO farbe(name, hexcode) values("amber darken-3", "#ff8f00");
INSERT INTO farbe(name, hexcode) values("amber darken-4", "#ff6f00");
INSERT INTO farbe(name, hexcode) values("amber accent-1", "#ffe57f");
INSERT INTO farbe(name, hexcode) values("amber accent-2", "#ffd740");
INSERT INTO farbe(name, hexcode) values("amber accent-3", "#ffc400");
INSERT INTO farbe(name, hexcode) values("amber accent-4", "#ffab00");
INSERT INTO farbe(name, hexcode) values("orange lighten-5", "#fff3e0");
INSERT INTO farbe(name, hexcode) values("orange lighten-4", "#ffe0b2");
INSERT INTO farbe(name, hexcode) values("orange lighten-3", "#ffcc80");
INSERT INTO farbe(name, hexcode) values("orange lighten-2", "#ffb74d");
INSERT INTO farbe(name, hexcode) values("orange lighten-1", "#ffa726");
INSERT INTO farbe(name, hexcode) values("orange", "#ff9800");
INSERT INTO farbe(name, hexcode) values("orange darken-1", "#fb8c00");
INSERT INTO farbe(name, hexcode) values("orange darken-2", "#f57c00");
INSERT INTO farbe(name, hexcode) values("orange darken-3", "#ef6c00");
INSERT INTO farbe(name, hexcode) values("orange darken-4", "#e65100");
INSERT INTO farbe(name, hexcode) values("orange accent-1", "#ffd180");
INSERT INTO farbe(name, hexcode) values("orange accent-2", "#ffab40");
INSERT INTO farbe(name, hexcode) values("orange accent-3", "#ff9100");
INSERT INTO farbe(name, hexcode) values("orange accent-4", "#ff6d00");
INSERT INTO farbe(name, hexcode) values("deep-orange lighten-5", "#fbe9e7");
INSERT INTO farbe(name, hexcode) values("deep-orange lighten-4", "#ffccbc");
INSERT INTO farbe(name, hexcode) values("deep-orange lighten-3", "#ffab91");
INSERT INTO farbe(name, hexcode) values("deep-orange lighten-2", "#ff8a65");
INSERT INTO farbe(name, hexcode) values("deep-orange lighten-1", "#ff7043");
INSERT INTO farbe(name, hexcode) values("deep-orange", "#ff5722");
INSERT INTO farbe(name, hexcode) values("deep-orange darken-1", "#f4511e");
INSERT INTO farbe(name, hexcode) values("deep-orange darken-2", "#e64a19");
INSERT INTO farbe(name, hexcode) values("deep-orange darken-3", "#d84315");
INSERT INTO farbe(name, hexcode) values("deep-orange darken-4", "#bf360c");
INSERT INTO farbe(name, hexcode) values("deep-orange accent-1", "#ff9e80");
INSERT INTO farbe(name, hexcode) values("deep-orange accent-2", "#ff6e40");
INSERT INTO farbe(name, hexcode) values("deep-orange accent-3", "#ff3d00");
INSERT INTO farbe(name, hexcode) values("deep-orange accent-4", "#dd2c00");
INSERT INTO farbe(name, hexcode) values("brown lighten-5", "#efebe9");
INSERT INTO farbe(name, hexcode) values("brown lighten-4", "#d7ccc8");
INSERT INTO farbe(name, hexcode) values("brown lighten-3", "#bcaaa4");
INSERT INTO farbe(name, hexcode) values("brown lighten-2", "#a1887f");
INSERT INTO farbe(name, hexcode) values("brown lighten-1", "#8d6e63");
INSERT INTO farbe(name, hexcode) values("brown", "#795548");
INSERT INTO farbe(name, hexcode) values("brown darken-1", "#6d4c41");
INSERT INTO farbe(name, hexcode) values("brown darken-2", "#5d4037");
INSERT INTO farbe(name, hexcode) values("brown darken-3", "#4e342e");
INSERT INTO farbe(name, hexcode) values("brown darken-4", "#3e2723");
INSERT INTO farbe(name, hexcode) values("grey lighten-5", "#fafafa");
INSERT INTO farbe(name, hexcode) values("grey lighten-4", "#f5f5f5");
INSERT INTO farbe(name, hexcode) values("grey lighten-3", "#eeeeee");
INSERT INTO farbe(name, hexcode) values("grey lighten-2", "#e0e0e0");
INSERT INTO farbe(name, hexcode) values("grey lighten-1", "#bdbdbd");
INSERT INTO farbe(name, hexcode) values("grey", "#9e9e9e");
INSERT INTO farbe(name, hexcode) values("grey darken-1", "#757575");
INSERT INTO farbe(name, hexcode) values("grey darken-2", "#616161");
INSERT INTO farbe(name, hexcode) values("grey darken-3", "#424242");
INSERT INTO farbe(name, hexcode) values("grey darken-4", "#212121");
INSERT INTO farbe(name, hexcode) values("blue-grey lighten-5", "#eceff1");
INSERT INTO farbe(name, hexcode) values("blue-grey lighten-4", "#cfd8dc");
INSERT INTO farbe(name, hexcode) values("blue-grey lighten-3", "#b0bec5");
INSERT INTO farbe(name, hexcode) values("blue-grey lighten-2", "#90a4ae");
INSERT INTO farbe(name, hexcode) values("blue-grey lighten-1", "#78909c");
INSERT INTO farbe(name, hexcode) values("blue-grey", "#607d8b");
INSERT INTO farbe(name, hexcode) values("blue-grey darken-1", "#546e7a");
INSERT INTO farbe(name, hexcode) values("blue-grey darken-2", "#455a64");
INSERT INTO farbe(name, hexcode) values("blue-grey darken-3", "#37474f");
INSERT INTO farbe(name, hexcode) values("blue-grey darken-4", "#263238");
INSERT INTO farbe(name, hexcode) values("black", "#000000");
INSERT INTO farbe(name, hexcode) values("white", "#ffffff");
